# cloudrun.yml
steps:

  - id: Snyk Open Source Test
    name: 'snyk/snyk-cli:npm'
    entrypoint: bash
    args:
      - '-c'
      - |-
        snyk config set api=${_SNYK_TOKEN}
        snyk test --severity-threshold=medium || true

  - id: Snyk Code Test
    name: 'snyk/snyk-cli:npm'
    entrypoint: bash
    args:
      - '-c'
      - |-
        snyk config set api=${_SNYK_TOKEN}
        snyk code test --severity-threshold=medium || true

  - id: Snyk Container Test
    name: 'snyk/snyk-cli:npm'
    entrypoint: bash
    args:
      - '-c'
      - >-
        snyk config set api=${_SNYK_TOKEN}
        snyk container test --severity-threshold=${_SEVERITY}
        ${_IMAGE_NAME}:$COMMIT_SHA


  - id: Snyk IaC Test
    name: 'snyk/snyk-cli:npm'
    entrypoint: bash
    args:
      - '-c'
      - |-
        snyk config set api=${_SNYK_TOKEN}
        snyk iac test --severity-threshold=medium main.tf || true

  - id: Create HTML artifact
    name: 'snyk/snyk-cli:npm'
    entrypoint: bash
    args:
      - '-c'
      - >-
        snyk config set api=${_SNYK_TOKEN}

        set -o pipefail

        snyk test --severity-threshold=medium --json | snyk-to-html -o
        results.html || true

  - id: Deploy to Cloud Run
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run','deploy','${_SERVICE_NAME}','--image ${_IMAGE_NAME}']
    

substitutions:
  _SERVICE_NAME: baseapi
  _IMAGE_NAME: gcr.io/$PROJECT_ID/baseui
  _SNYK_TOKEN: ''
  _BUILDER: paketobuildpacks/builder:base
  _SEVERITY: medium

images:
 - '${_IMAGE_NAME}'

artifacts:
  objects:
    location: 'gs://cloud-build-artifacts/scan_output'
    paths:
      - results.html
